describe("Testcase for login", function(){
    it("Positive testcase", function(){
      cy.fixture("Credentials").then((Credential) =>{
        cy.visit("https://automationexercise.com/login")
        cy.get('[data-qa="login-email"]').type(Credential.Email_Address)
        cy.get('[data-qa="login-password"]').type(Credential.password)
        cy.get('[data-qa="login-button"]').click()
        cy.contains('Products').click()
        cy.get(':nth-child(3) > .product-image-wrapper > .choose > .nav > li > a').click()
        cy.get('#quantity').clear().clear().type(3)
        cy.get(':nth-child(5) > .btn').click()
        cy.wait(3000)
        cy.get('u').click()
        cy.wait(3000)
        cy.get('.col-sm-6 > .btn').click()
        cy.get(':nth-child(7) > .btn').click()
        cy.get('[data-qa="name-on-card"]').type("waseem")
        cy.get('[data-qa="card-number"]').type(Credential.card_number)
        cy.get('[data-qa="cvc"]').type(Credential.cvc)
        cy.get('[data-qa="expiry-month"]').type(Credential.month)
        cy.get('[data-qa="expiry-year"]').type(Credential.year)
        cy.get('[data-qa="pay-button"]').click()
        cy.get('.col-sm-9 > .btn-default').click()
        cy.wait(3000)
        cy.get('[data-qa="continue-button"]').click()
      })
    })
})