console.log("Welcome to software Automation testing")
describe("Automation testing", function (){
 
  it("Positve Test case for login", function(){
    cy.fixture("Credentials").then((Credentials) =>{
      cy.visit("https://automationexercise.com/login")
      cy.get('[data-qa="signup-button"]').type("waseem")
      cy.get('[data-qa="signup-email"]').type("user12@gmail.com")
      cy.get('[data-qa="signup-button"]').click()
      cy.get('#id_gender1').click()
      cy.wait(3000)
      cy.get('[data-qa="password"]').type(Credentials.password)
      cy.wait(3000)
      cy.get('[data-qa="days"]').select("29")
      cy.wait(3000)
      cy.get('[data-qa="months"]').select("December")
      cy.wait(3000)
      cy.get('[data-qa="years"]').select("2001")
      cy.wait(3000)
      cy.get('[data-qa="first_name"]').type("Waseem")
      cy.wait(3000)
      cy.get('[data-qa="last_name"]').type("Sajjad")
      cy.wait(3000)
      cy.contains('Company').type("Binyaapi Holdings")
      cy.wait(3000)
      cy.get('[data-qa="address"]').type("1234 Maple Street SW Calgary, AB T2P 3N4 Canada")
      cy.wait(3000)
      cy.get('[data-qa="country"]').select("Canada")
      cy.wait(3000)
      cy.get('[data-qa="state"]').type("Calgary")
      cy.wait(3000)
      cy.get('[data-qa="city"]').type("Maple")
      cy.wait(3000)
      cy.get('[data-qa="zipcode"]').type("1234")
      cy.wait(3000)
      cy.get('[data-qa="mobile_number"]').type("03154519990")
      cy.wait(3000)
      cy.get('[data-qa="create-account"]').click()
      cy.get('[data-qa="continue-button"]').click()
      cy.url("https://automationexercise.com/login")
      cy.get('[data-qa="login-email"]').type(Credential.Email_Address1)
      cy.get('[data-qa="login-password"]').type(Credential.password)
      cy.get('[data-qa="login-button"]').click()
    })
  })
})